100-hours-a-week/15-Leafresh-FE

src/app/layout.tsx, src/shared/components/Wrapper/GridBox.tsx, src/shared/config/providers/ChakraProvider.tsx, src/shared/config/providers/Providers.tsx
Relates to #17 
```
export function Providers({ children }: { children: ReactNode }) {
return <EmotionCacheProvider><ChakraUseProvider>{children}</ChakraUseProvider></EmotionCacheProvider>
}
```
```
<GridBox columns={2} rowGap="10px" columnGap="10px">
{items}
</GridBox>
```
또한, rowGap과 columnGap을 사용해서 item간의 가로세로 거리를 조절할 수있습니다.
Chakra UI의 GridProps는 다음과 같은 데이터가 제공됩니다. 필요할 시 사용 가능합니다. 필요 시, 사용 가능합니다.
childWidth를 사용 시, auto-fit이 되어 혼란이 발생할 수 있으니, child item의 width를 설정하고 사용하는 것을 권장합니다.
```
/** 고정 너비 기반 동적 컬럼 (auto-fit/minmax) */ 
childWidth?: string 
/** 아이템 수평 정렬 */
justifyItems?: GridProps['justifyItems']
/** 아이템 수직 정렬 */
alignItems?: GridProps['alignItems']
/** 그리드 컨테이너 수평 정렬 */
justifyContent?: GridProps['justifyContent']
/** 그리드 컨테이너 수직 정렬 */
alignContent?: GridProps['alignContent']
/** …
```
=> FE: PR[feat] GridBox Implementation

package.json
해당 링크의 노션 페이지를 통해 로컬 환경에서 TLS를 적용해야 하는 이유를 작성하고 있습니다.
간략히 정리하면, 로컬과 배포 서버의 쿠키 교환을 위해서 secure, samesite = none 을 설정하면, TLS 환경에서만 쿠키를 교환할 수 밖에 없기 때문입니다.
앞으로 개발할 때는 무조건 https://로 될 겁니다.
=> feat: dev 환경 https 설정

next.config.ts, src/features/member/api/signup.ts, src/shared/components/Toast/Toast.tsx, src/shared/components/switchtap/SwitchTap.tsx, src/shared/components/timepicker/TimeDropdown.tsx, src/shared/constants/endpoint/endpoint.ts, src/shared/hooks/useImageUpload/useImageUpload.ts
이미지 업로드 훅 구현
-
Relates to #65
Closes #69 
```
const uniqueId = crypto.randomUUID()
const uniqueName = `${Date.now()}-${uniqueId}-${file.name}`
try {
const signed = await fetchRequest<signedUrlResponse>(ENDPOINTS.S3.PRESIGNED_URL, {
body: {
fileName: uniqueName,
contentType: file.type,
},
})
```
Node.js에서 제공해주는 랜덤 값 생성과, 현재 timestamp를 파일 이름에 붙여 presigned url을 받아오는 방법으로 해결했습니다.
```
// loading은 boolean 값으로 업로드 중이면 true, 업로드가 완료되면 false
const { uploadFile, loading, error } = useImageUpload()
const [imageUrl, setImageUrl] = useState<string | null>(null)
try {
// 파일 업로드 → 공개 URL 반환
const url = await uploadFile(file)
setImageUrl(url) //원하는 방식으로 적재
} catch {
// 에러는 훅의 error 상태에 setting 되어 있음
console.error(error)
}
}
```
=> FE: feat useImageUpload Implementation

src/app/layout.tsx, src/shared/components/Modal/camera-modal/CameraModal.tsx
- 카메라 관련 에러 코드 수정
Relates to #76 
Closes #90 
``` typescript
// 카메라 초기화 및 정리 효과
useEffect(() => {
if (isOpen && !previewUrl) {
setScrollTop(window.scrollY)
startCamera()
}
return () => {
// 컴포넌트 언마운트 또는 의존성 변경 시 항상 카메라 정리
stopCamera()
}
}, [isOpen, previewUrl, facingMode]) //수정 전에는 isOpen만 의존성 배열에 존재
```
위의 useEffect코드에서 facingMode에 대한 의존성이 사라져서 생긴 문제였습니다.
``` typescript
// facingMode 변경 시 카메라 재시작-> 같은 기능을 하는 useEffect가 충돌
// useEffect(() => {
//   if (isOpen && !previewUrl) {
//     startCamera()
//   }
// }, [facingMode])
```
cameraModal 코드의 startCamera에서 전후면 전환 시에 카메라 정리 및 재시작을 하는데, 같은 기능의 useEffect가 2개 존재해서 생긴 문제였습니다. 해당 코드는 주석 처리하였습니다.
- 주요 변경점은 위의 2가지입니다.
=> PR [fix] 카메라 모달 전후면 전환 및 사용 에러 핸들링

src/app/(with-header)/challenge/group/[id]/modify/page.tsx, src/app/(with-header)/challenge/group/create/page.tsx, src/app/(with-header)/member/signup/page.tsx, src/features/challenge/api/create-group-challenge.ts, src/features/challenge/api/get-group-challenge-rules.ts, src/features/challenge/api/modify-group-challenge.ts, src/features/challenge/api/verify-personal-challenge.ts, src/features/challenge/components/challenge/group/GroupChallengeFormPage.tsx, src/features/challenge/components/challenge/group/create/DetailStep.tsx, src/features/challenge/components/challenge/group/create/GroupChallengeCreatePage.tsx, src/features/challenge/components/challenge/group/create/MetadataStep.tsx, src/features/challenge/components/challenge/group/modify/ChallengeGroupModifyPage.tsx, src/features/challenge/components/challenge/personal/details/ChallengePersonalDetails.tsx, src/features/challenge/components/common/ChallengeVerifyExamples.tsx, src/features/challenge/components/common/VerificationImageInput.tsx, src/shared/components/Modal/camera-modal/CameraModal.tsx, src/shared/components/Modal/camera-modal/VerificationGuideModal.tsx, src/shared/components/check-icon/CheckIcon.tsx, src/shared/config/tanstack-query/mutation-defaults.ts, src/shared/config/tanstack-query/mutation-keys.ts, src/shared/constants/endpoint/endpoint.ts, src/shared/styles/GlobalStyle.tsx
단체 챌린지 수정 페이지 구현
Relates to #98
Closes #101
Closes #122 
1. 단체 챌린지 상세 조회
2. 기존 "단체 챌린지 생성" 페이지를 재활용하여, 디폴트 값을 기존 데이터로 채우기
3. 하나의 컴포넌트에서 생성, 수정을 담당하므로, `props`에 따라 `Mutation` 선정
- 챌린지 생성/수정 예시 이미지 조건 변경 #122 
- 썸네일 촬영 시 체크 애니메이션 추가
=> FE: PR(feat) 단체 챌린지 수정 페이지 구현

src/app/(with-layout)/(with-header)/challenge/personal/[id]/ChallengePersonalDetails.tsx, src/app/(with-layout)/layout.tsx, src/features/challenge/api/get-personal-challenge-details.ts, src/features/challenge/api/verify-personal-challenge.ts, src/features/challenge/hook/use-personal-verification-result.ts, src/shared/components/modal/camera-modal/CameraModal.tsx, src/shared/config/providers/PollingWatcher.tsx, src/shared/config/providers/QueryClientProvider.tsx, src/shared/context/polling/PollingStore.ts
개인 챌린지 인증을 제출한 경우, 롱폴링으로 인증 결과를 수령하며 / 전역에서 수행하여 어디서든지 결과를 받아볼 수 있도록 구현합니다.
- 전역 레이아웃에서, 로컬 스토리지에 담긴 id들을 토대로, 롱폴링을 요청하는 감시 컴포넌트를 만들었습니다
Relates to #232 
Closes #236
=> FE: PR (feat) 개인 챌린지 인증 제출 롱폴링 전역 수행 로직 구현  

.github/workflows/fe-cicd.yml
> tag 이름 중 v가 사라지는 현상 수정
> tag 규칙 상 . 같은 특수기호가 앞에 오면 안되는데, tag_name 전처리 중 'v'가 사라져 오류가 발생하는 현상을 발견해 수정함.
Relates to #none
Closes #none
=> feat: tag 전처리 중 v 삭제되는 현상 수정

src/middleware.ts
미들웨어의 코드 직접 변경으로 진행되던 점검중 환경 체킹을 GCS 버킷의 특정 파일의 존재 유무를 통해 수행하도록 변경하였습니다.
단, 로컬 및 Prod 환경에서는 점검 유무를 판단하지 않아도 되므로, hostname을 토대로 점검중 페이지가 뜨지 않도록 하였습니다.
Closes #266
=> feat: 점검중 페이지 배포환경 파일 체킹으로 변경

.github/workflows/fe-cicd.yml, next.config.ts
> 이미지 허용 url의 pathname을 동적으로 할당합니다.
기존에 사용하던 환경변수에서 환경에 대한 정보를 담고 있는 비밀값 (NEXT_PUBLIC 기반 공개값), 각 개발환경의 허용 가능한 이미지 경로를 설정하였습니다.
```typescript
let gcsHostname: string
switch (runtimeEnv) {
case 'local':
gcsHostname = 'leafresh-images'
break
case 'dev':
gcsHostname = 'leafresh-images'
break
case 'prod':
gcsHostname = 'leafresh-prod-images'
default:
throw new Error(`Unknown Image Route NEXT_PUBLIC_RUNTIME: ${runtimeEnv}`)
}
```
```typescript
{
protocol: 'https',
hostname: 'storage.googleapis.com', // 정확히 이 도메인이어야 함
pathname: `/${gcsHostname}/**`, // 해당 경로 하위 모든 이미지 허용
},
```
```typescript
{
protocol: 'http',
hostname: '*.kakaocdn.net',
},
```
CI/CD Lint 단계에서 `.env`가 도커 이미지에 주입되지 않는 오류를 클라우드팀과 함께 해결하였습니다.
`fe-ci/cd.yml` 파일을 확인해주세요!
Closes #279
=> PR:[feat] 환경 별 이미지 허용 pathname 할당

Dockerfile
> Dockerfile 수정
- Dockerfile `CMD`를 수정하여 `metrics-server.ts`를 백그라운드로 실행하도록 변경
- `pnpm run start`와 함께 동시에 실행되도록 쉘 명령(`sh -c`) 사용
- Prometheus 메트릭 수집을 위한 9103 포트 EXPOSE 추가
Relates to #number
Closes #number
=> CL : 모니터링 서비스 백그라운드 실행 코드로 변경 (Dockerfile)

Dockerfile, scripts/metrics-server.js
> Prometheus 메트릭 수집을 위한 `metrics-server.js` 실행을 Dockerfile에 추가
> 
- CMD를 `node scripts/metrics-server.js & pnpm run start`로 변경하여 Next.js와 메트릭 서버가 함께 실행되도록 구성
- 9103 포트 EXPOSE 추가 (Prometheus scrape용)
- 기존 파일에서 타입스크립트를 사용하지 않으므로 `.js` 파일로 변환
- tsconfig 구조 상 TypeScript 빌드가 불가능한 환경을 고려한 조치
=> feat: metrics-server.js 실행 추가 및 Dockerfile CMD 수정

src/features/challenge/components/form-detail-step/thumbnail-image-input.tsx, src/features/challenge/components/group-challenge-card/group-challenge-card.tsx, src/features/challenge/components/verification-card/verification-card.tsx, src/features/main/components/event-section/event-section.tsx, src/features/main/components/personal-challenge-section/personal-challenge-section.tsx, src/shared/components/modal/camera-modal/camera-modal.tsx, src/shared/constants/image-size.ts, src/widgets/challenge/group/[id]/details/challenge-group-details.tsx, src/widgets/challenge/group/[id]/verification/details/challenge-group-verification-details.tsx, src/widgets/challenge/group/feed/challenge-group-feed.tsx, src/widgets/challenge/personal/[id]/details/challenge-personal-details.tsx
모바일 환경에서 이미지를 촬영하는 경우, 원하지 않는 크기로 나오던 현상을 해결하였습니다.
기존에 사용하던 `ASEPCT_RATIOS` 라는 변수에 챌린지의 썸네일 이미지, 인증 이미지 비율을 고정하여 사용하도록 변경하였습니다.
- 챌린지 썸네일 이미지 : 14/9
- 챌린지 인증 이미지 : 5/3
Closes #333
=> PR FE (bug/chore) : 이미지 비율 불일치 현상 해결 및 모바일 환경의 video 크기 조정

next.config.ts, src/features/main/components/personal-challenge-section/personal-challenge-section.tsx, src/features/store/components/ongoing-timedeal-card/ongoing-timedeal-card.tsx, src/features/store/components/ongoing-timedeal-list/ongoing-timedeal-list.tsx, src/features/store/components/product-card/product-card.tsx, src/features/store/components/product-list/product-list.tsx
나뭇잎 상점에서 나뭇잎 개수가 추가됨에 따라, 상품 구매시 낙관적 업데이트 적용 및 나뭇잎 개수가 부족한 경우에 대한 예외처리를 토스트로 진행하였습니다.
업데이트 상황
- 일반 상품 구매
- 특가 상품 구매
- 나뭇잎 개수가 부족한 경우, 구매 실패
- 낙관적 업데이트에 따라, 재고 유무를 백엔드에서 받은 데이터가 아닌 낙관적 업데이트를 위해 관리하는 재고로 판단합니다.
---
Relates #341
Closes #342
=> PR FE (fix) : 나뭇잎 상점 개수 낙관적 업데이트 및 개수 예외 처리

src/features/main/components/group-challenge-section/styles.ts, src/features/store/components/product-card/product-card.tsx, src/features/store/components/product-card/styles.ts, src/widgets/challenge/group/feed/styles.ts, src/widgets/member/profile/modify/styles.ts
iOS에서 오적용되는 스타일 코드를 수정하였습니다.
iOS Safari `display: grid` 에서는 가로 스크롤이 필요한 경우에도 컨테이너 크기를 잘 넘기지 않는다고 합니다.
display : grid는 고정된 크기의 요소에 사용하는 것은 권장한다고 합니다.
따라서, `display: flex`로 변경하였습니다.
또한, 각 요소의 크기가 작아지는 것에 대응하기 위해 `flex-shrink : 0`로 크기를 고정하였습니다.
Relates #332
Closes #358
=> PR FE (fix) : 크로스 브라우징 스타일 에러 해결

src/app/(with-layout)/(with-header)/page.tsx, src/shared/config/tanstack-query/query-client.ts, src/shared/config/tanstack-query/query-defaults.ts, src/widgets/challenge/group/[id]/verification/details/challenge-group-verification-details.tsx
<h1>요약</h1>
<blockquote>
<p>작업내용을 간략히 작성합니다.</p>
</blockquote>
<p>SSR에서 prefetchQuery로 데이터를 미리 받아왔음에도, 클라이언트에서 동일한 쿼리를 중복 요청하는 문제를 해결했습니다.</p>
<h2>변경사항</h2>
<blockquote>
<p>변경사항을 항목별로 자세히 작성합니다.</p>
</blockquote>
<h2><strong>1. staleTime 기본값을 0이 아닌 값으로 설정</strong></h2>
<p>테스트 결과, CSR의 staleTime이 0보다 크면 <strong>SSR에서 미리 패칭된 데이터</strong>를 그대로 재사용하고, <strong>중복 요청이 발생하지 않는 것</strong>을 확인했습니다.</p>
SSR (prefetchQuery) StaleTime | CSR (useQuery) StaleTime | CSR 리페치 여부
-- | -- | --
0 | 0 | ⭕️
0 | not 0 | ❌
not 0 | 0 | ⭕️
not 0 | not 0 | ❌
<p>기존에는 Tanstack Query 기본 설정대로 <code>staleTime: 0</code>을 사용해왔으나,</p>
<p>이는 SSR에서 받은 데이터를 클라이언트가 곧바로 <strong>stale 상태로 간주</strong>하게 되어, 리페치가 발생하는 원인이었습니다.</p>
<h3>어떤 값으로 설정?</h3>
<ul>
<li><code>staleTime</code>을 너무 크게 설정하면 최신 데이터 반영이 늦어지며</li>
<li>다시 0으로 두면 중복 …
=> PR FE (fix) :  SSR 이후 CSR에서 불필요한 refetch 제거

src/app/(with-layout)/(with-header)/member/challenge/participate/list/page.tsx, src/shared/components/navbar/consts.ts, src/shared/constants/route.ts, src/shared/lib/utils/build-uri.ts, src/shared/lib/utils/index.ts, src/widgets/challenge/group/[id]/details/challenge-group-details.tsx, src/widgets/member/challenge/participate/list/member-challenge-participate-list.tsx, src/widgets/member/challenge/verification/status/member-challenge-verification-status.tsx
> 작업 내용을 간략히 정리합니다.
단체 챌린지에 참여한 직후, 사용자가 해당 챌린지를 확인할 수 없는 탭으로 라우팅되는 문제가 있었습니다.
사용자 혼란을 줄이기 위해, 참여 직후 “인증 대기” 탭으로 이동하도록 개선하였으며, 이를 위해 status 값을 URL 쿼리 파라미터로 추가하도록 구현했습니다.
`buildURI` 함수는 `query`와 `fragment` 값을 받아, 이를 포함한 URI 문자열을 생성합니다.
이제부터 query 또는 fragment를 포함한 URL을 생성할 때는 아래 함수를 사용해주세요.
```tsx
export interface UrlBuilderOptions {
query?: Record<string, string | number | boolean | undefined | null>
fragment?: string
}
/**
* 경로에 쿼리스트링과 해시(fragment)를 붙여주는 함수
* @param path 기본 URL 경로
* @param options query 객체, fragment 문자열
* @returns ex) '/challenge/group/list?category=food&page=2#section1'
*/
export const buildURI = (path: string, options?: UrlBuilderOptions): string => {
const { query, fragment } = options || {}
const searchParams = new URLSearchParams()
if (query) …
```
=> PR FE (feat) : 단체 챌린지 참여 후, "인증 대기"로 라우팅 되도록 변경

.github/workflows/fe-cicd.yml
> gcloud용 액션 추가
> `gcloud scp`와 `gcloud ssh`를 사용하기 위한 공식 액션 적용
> FE용 서비스 계정 키 발급 및 secrets 적용
=> Fix: gcloud action 추가

src/features/challenge/components/feed-list/feed-list.tsx
피드 페이지에서 사용중인 무한스크롤 옵저버의 메모리를 할당하는 로직 추가
Relates to #373
=> PR FE (fix): 피드 리스트 무한스크롤 옵저버 해제

src/features/store/components/ongoing-timedeal-list/ongoing-timedeal-list.tsx
나뭇잎 개수가 0인 경우, falsy로 판단되어 `LeafReward` 컴포넌트가 정상 렌더링되지 않는 오류를 해결했습니다.
`undefined`인 경우를 분기처리하도록 하였습니다.
```tsx
{/* {memberLeafCount && <S.StyledLeafReward reward={memberLeafCount} />} */}
{memberLeafCount !== undefined && <S.StyledLeafReward reward={memberLeafCount} />}
```
Relates to #341
Closes #407
=> fix: 나뭇잎 개수가 0개인 경우에도 정상적 렌더링 표시

src/entities/challenge/api/group/get-group-details.ts, src/widgets/challenge/group/[id]/details/challenge-group-details.tsx
단체 챌린지 상세 페이지의 버튼의 라벨과 버튼 클릭 시 로직을 수정하였습니다.
기존 인증 여부를 판단하는 4가지 상태인 `NOT_SUBMMITED | PENDING_APPROVAL | SUCCESS | FAILURE`를 포함하여, 하나의 상태가 추가된 `NOT_PARTICIPATED`를 추가하였습니다.
`NOT_PARTICIPATED`는 참여하지 않은 상태를 의미합니다.
참여하지 않은 경우 / 참여 후 인증 과정에 따라 라벨 내용을 분기 처리하였습니다.
2번의 라벨의 변경사항에 따라, 참여 후 인증 과정에 있는 경우 버튼 클릭 시 인증 상태 페이지로 라우트 되도록 설정하였습니다.
Closes #414
Closes #415
=> PR (FE) fix: 단체 챌린지 인증 버튼 / 라벨 동기화
