package.json, pnpm-lock.yaml, src/app/(with-header)/store/page.tsx, src/shared/components/dropdown/index.tsx, src/shared/components/errortext/index.tsx, src/shared/components/input/index.tsx
- 입력을 받을 수 있는 Input 컴포넌트를 제작했습니다.
- `controlled` (값을 지속적으로 추적) 하는 방식으로 제작하였습니다.
https://github.com/user-attachments/assets/c7afef31-6eac-4e17-aad9-8a2d8ca005e8
Relates to #17
Closes #54 
기존 Dropdown에서는 `::before` 을 이용하여 포커스간 애니메이션 처리를 하였지만, input 요소는 Self Closing 태그 (`<input />`)여서 해당 ::before이 없는 점을 고려하여 `<Underline />`을 제작하였습니다.
=> FE: PR(Feat) Input Component Implementation

src/features/challenge/api/get-event-challenge-list.ts, src/features/challenge/components/challenge/ChallengeMainPage.tsx, src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx, src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx, src/shared/components/Modal/ConfirmModal.tsx, src/shared/components/Modal/camera-modal/CameraModal.tsx, src/shared/components/chatbot/ChatBubble.tsx, src/shared/components/chatbot/ChatFrame.tsx, src/shared/components/chatbot/ChatHeader.tsx, src/shared/components/chatbot/ChatSelection.tsx, src/shared/components/chatbot/Chatbot.tsx, src/shared/components/slide-drawer/SlideDrawer.tsx
QA 에러 수정
-
Relates to #76 
Closes #86
=> PR: [fix] QA 수정

src/features/challenge/components/challenge/ChallengeMainPage.tsx, src/features/challenge/components/challenge/group/create/MetadataStep.tsx
단체 챌린지 기타 카테고리 선택지를 삭제하였습니다.
단, 기존 상수값은 유지해두겠습니다. (기획 변경에 대비..)
Closes #116
=> FE: PR(chore) 단체 챌린지 기타 카테고리 삭제

src/features/chatbot/chatbot-base-info.ts, src/features/chatbot/chatbot-free-text.ts, src/shared/components/chatbot/ChatFrame.tsx, src/shared/components/chatbot/ChatSelection.tsx
- 챗봇 응답 api의 request body 데이터 추가
- 스크롤바 조정
- 선택지 이미지 크기 조정
Relates to #87 
Closes to #95 
- 다른 기능 추가는 이슈 새로 파도록 하겠습니다.
=> PR:[refactor] 챗봇 api

.gitignore, package.json, playwright.config.ts, pnpm-lock.yaml, tests-examples/demo-todo-app.spec.ts, tests/example.spec.ts
=> v1.0.5 / Playwright 설치

package.json
=> chore: 테스트 명령어 생성 (pnpm test:e2e)

src/features/challenge/components/challenge/group/list/ChallengeListPage.tsx, src/features/challenge/hook/useGroupChallengeList.ts
아무 챌린지도 보여지지 않던 현재 오류를 해결했습니다.
=> FE: (PR) 특정 카테고리 챌린지 추출 오류

.github/workflows/fe-cicd.yml
- github actions에서 build 단계를 PR에서 수행하도록 변경
Relates to #none
Closes #none
- 이제 build 단계도 PR 요청 시 실행되게 됩니다.
- build 단계 실행 중에 아래와 같은 에러가 발생합니다! 참고하시라고 올려놓겠습니다.
```
#13 46.27 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/app/api-reference/config/eslint#disabling-rules
#13 49.55    Collecting page data ...
#13 51.90    Generating static pages (0/13) ...
#13 53.00    Generating static pages (3/13) 
#13 53.00    Generating static pages (6/13) 
#13 53.80    Generating static pages (9/13) 
#13 113.7 Failed to build /(with-header)/member/challenges/page: /member/challenges (attempt 1 of 3) because it took more than 60 seconds. Retrying again shortly.
#13 174.4 Failed to build /(with-header)/member/challenges/page: /member/challenges (attempt 2 of 3) because it …
```
=> Update: build 단계 if 조건 변경

.github/workflows/fe-cicd.yml
- ENV 등록 완료
Relates to #none
Closes #none
=> Feature/feat/cicd dev: ENV 등록 완료

.github/workflows/discord-notification.yml
- PR 만들 때만 알람 옵니다!
Relates to #none
Closes #none
=> PR: PR 생성했을 때만 알림 오는 액션 파일

src/shared/lib/api/client-fetcher/client-fetcher.ts, src/shared/lib/api/fetcher/fetcher.ts
=> fix: 엔드포인트 테스트

src/app/(with-layout)/(with-header)/MainPage.tsx, src/app/(with-layout)/(with-header)/page.tsx, src/shared/lib/api/client-fetcher/client-fetcher.ts, src/shared/lib/api/server-fetcher/server-fetcher.ts
=> fix: 엔드포인트 서버 테스트

Dockerfile
-
Relates to #number
Closes #number
=> fix: dockerfile next.config.ts 포함

Dockerfile
-
Relates to #number
Closes #number
=> fix : Dockerfile

Dockerfile, src/app/(with-layout)/(with-header)/MainPage.tsx, src/app/(with-layout)/(with-header)/member/[provider]/callback/CallbackPage.tsx, src/app/(with-layout)/(with-header)/member/signup/page.tsx, src/app/(with-layout)/(with-header)/store/page.tsx, src/features/challenge/api/get-group-challenge-categories.ts, src/features/challenge/api/get-group-challenge-list.ts, src/features/challenge/api/participate/get-group-participant-list.ts, src/features/challenge/api/participate/verification/get-verifycation-details.ts, src/features/challenge/components/challenge/group/feed/FeedList.tsx, src/features/challenge/components/challenge/participate/ChallengeParticipatePage.tsx, src/features/challenge/components/challenge/participate/GroupChallengeParticipantCard.tsx, src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx, src/features/challenge/components/challenge/participate/list/ChallengeGroupParticipateList.tsx, src/features/challenge/components/challenge/participate/verification/details/VerificationDetails.tsx, src/features/challenge/components/challenge/participate/verification/verification-card.tsx, src/features/main/components/sections/group-challenge-section.tsx, src/features/member/components/member/profile/mypage/Mypage.tsx, src/features/store/components/product/ProductCard.tsx, src/features/store/components/product/ProductList.tsx, src/features/store/hook/useInfiniteProducts.ts, src/shared/components/modal/camera-modal/CameraModal.tsx, src/shared/config/providers/QueryClientProvider.tsx, src/shared/constants/endpoint/endpoint.ts, src/shared/constants/route/route.ts, src/shared/lib/api/client-fetcher/client-fetcher.ts, src/shared/lib/api/client-fetcher/client-reissue.ts, src/shared/lib/api/fetcher/fetcher.ts, src/shared/lib/api/server-fetcher/server-fetcher.ts, src/shared/lib/api/server-fetcher/server-reissue.ts
- 나뭇잎 상점 물품 검색
- 인증 내역 목록 검색
- 토큰 재발급 로직 경로 설정 오류
- 로그인, 회원가입 시 로그인 확인 처리
- 챌린지 인증 실제 데이터 반영
=> FE: (PR) feat API 연결 및 QA

src/app/(with-layout)/(with-header)/layout.tsx, src/features/challenge/components/member/alarm/MemberAlramList.tsx, src/features/store/api/order-proudcts.ts, src/features/store/components/product/ProductCard.tsx, src/shared/constants/endpoint/endpoint.ts
상품 주문 엔드포인트 설정 관련 휴먼 에러를 해결하였습니다.
1. 일반 상품 구매 멱등키 구매
2. 엔드포인트 재설정
3. 도착알림이 없을 때 에러 텍스트의 위치를 중앙으로 수정
=> fix: 상품 주문 엔드포인트 변경

src/app/(with-layout)/(with-header)/challenge/group/feed/FeedPage.tsx, src/entities/member/context/OAuthUserStore.ts, src/features/challenge/components/challenge/group/create/DetailStep.tsx, src/features/challenge/components/challenge/participate/GroupVerificationPage.tsx, src/features/challenge/components/challenge/participate/verification/VerificationCarousel.tsx, src/features/challenge/components/challenge/participate/verification/details/VerificationDetails.tsx, src/features/member/components/member/profile/mypage/Mypage.tsx, src/features/store/components/product/ProductCard.tsx, src/features/store/components/time-deal/OngoingTimeDealCard.tsx, src/features/store/components/time-deal/OngoingTimeDealList.tsx, src/features/store/components/time-deal/TimeDealList.tsx, src/features/store/components/time-deal/UpcomingTimeDealList.tsx, src/shared/components/loading/index.tsx
스타일 및 누락된 로직을 추가합니다.
- 스타일 인증 캐러셀 중앙 정렬
- 피드 페이지 카테괴 페칭 오류 해결
- 로그아웃 로직 추가
- 일반 상품 및 특가 상품 낙관적 업데이트 추가
=> FE: PR (fix) v2 배포 오류 테스트

src/features/challenge/components/verification-card/verification-card.tsx
인증 탭에서 클립보드 복사 클릭 시 인증 상세 페이지로 이동되는 오류 해결
Closes #247
=> fix: 클립보드 복사 시 라우팅 되는 오류 해결

src/middleware.ts
프론트 점검 데브에서 삭제
Relates to #242
=> fix: 서비스 시간 점검 데브에서는 삭제

src/features/challenge/api/group/verification/use-create-group-verification.ts, src/features/challenge/components/verification-carousel/verification-carousel.tsx, src/features/challenge/components/verification-status-card/verification-status-card.tsx, src/features/common/components/polling-watcher/polling-watcher.tsx, src/middleware.ts, src/shared/components/modal/camera-modal/camera-modal.tsx, src/widgets/member/challenge/verification/status/member-challenge-verification-status.tsx
- v2의 발견된 에러를 수정합니다.
- 'conpleted'로 캐싱된 데이터를 `getQueryClient`를 사용하여 비교하여 종료된 챌린지인지 확인합니다.
Closes #295
=> PR:[feat] v2 leafresh QA, 에러 수정

src/middleware.ts
> middleware maintenance 강제 이동 조건 변경
Closes #307
=> PR:[fix] middleware maintenance 강제 이동 조건 변경

src/features/challenge/components/challenge-participant-card/challenge-participant-card.tsx, src/widgets/member/challenge/participate/list/member-challenge-participate-list.tsx
- KST 변환 중간 과정 추가
- dev 배포 환경에서 적용되지 않는 이슈가 있어 Date 형식의 데이터를 ISO KST로 바꾼 뒤 00-00-00 로 변환하도록 하였습니다.
Relates to #309 
Closes #309
=> PR:[fix] KST 변환 중간 과정 추가

.github/workflows/fe-cicd.yml
=> PR:[fix] cicd 코드 env 주입 방식 통일

src/shared/lib/api/utils.ts
- dev환경 api 외부망 연결
- dev환경 api 외부망 연결
=> feat: dev환경 api 외부망 연결

src/app/api/proxy/[...path]/route.ts
=> PR[fix]: dev proxy route 수정

Dockerfile
> Dockerfile 수정
> Dockerfile에 `COPY --from=builder /app/scripts ./scripts` 구문 추가
> Prometheus 메트릭 서버 등 런타임에 필요한 스크립트 실행을 위함
Relates to #number
Closes #number
=> 모니터링 환경 구축을 위한 Dockerfile 수정 (dev instance)

.github/workflows/fe-cicd.yml
prod CI/CD 환경을 구축하며, 태그가 아닌 PR 푸시 단위로 재배포 되도록 변경되었습니다.
Closes #346
=> feat: prod ci/cd 반영 및 PR 푸시 단위로 변경

.github/workflows/fe-cicd.yml
=> fix: 빌드 전 env 주입

.github/workflows/fe-cicd.yml
=> chore: 통합 테스트 주석 처리

src/shared/components/introduce/introduce.tsx, src/shared/components/introduce/styles.ts, src/shared/components/modal/camera-modal/styles.ts, src/shared/components/switchtap/switch-tab.tsx, src/widgets/main/main.tsx, src/widgets/member/alarm/list/member-alarm-list.tsx, src/widgets/member/alarm/list/styles.ts
QA 및 유저 피드백 내용을 반영하였습니다.
1. Introduce 만개가 넘어가면 UI가 흔들림
[참고 영상]
https://github.com/user-attachments/assets/96587add-2589-4078-b55e-433799622a4a
2. 알림 클릭시 해당 챌린지로 이동하도록 변경
3. 이벤트 챌린지 영역 임시로 안보이도록 설정
4.  모바일 - 위 아래 영역으로 인한 카메라 모달 영역 축소
Closes #345
Closes #348
=> PR FE (fix): QA 핸들링 및 카메로 모달 헤더 크기 고정 (크로스 브라우징)

src/shared/components/modal/camera-modal/styles.ts, src/shared/constants/image-size.ts
=> PR FE (fix) : 카메라 모달 짤림 이슈 

src/middleware.ts
미들웨어 점검 상태 휴먼 에러를 해결하여 다시 업로드합니다. (조건 상태 확인 실수)
=> fix: 점검중 상태 조건 실수

.github/workflows/fe-cicd.yml, Dockerfile
> Prod 환경의 CI/CD 로직 변경 
> 인스턴스에서 빌드 후 실행하던 로직 &rarr; Github actions에서 빌드 후 인스턴스로 복사 및 실행으로 변경
=> fix: prod ci/cd 변경 및 Dockerfile 명시적 파일 복사

.github/workflows/fe-cicd.yml
> merge 이후에도 액션 실행 안되는 문제 해결
> if 구문 및 needs 구문 수정 및 추가로 PR 상태 및 merge 상태를 추적하여 액션 job을 실행할 지 확인하는 로직 추가
=> fix: CI/CD 실행 안되는 문제 해결

.github/workflows/fe-cicd.yml
> 이미지 빌드 문제 해결 및 gcloud cli 적용
> 1. CI/CD 중 이미지 빌드 문제: env를 주입하지 않아 에러 발생 <br>&rarr; Dockerfile에서 ARG 선언 및 도커 이미지 빌드 시 secrets 삽입으로 해결
> 2. gcloud 인식 불가 문제: gcloud action을 추가하지 않아 에러 발생 <br>&rarr; 깃허브 공식 gcloud 액션을 적용해 해결
=> Fix: Prod용 CI/CD 문제 해결

src/app/(with-layout)/(with-header)/challenge/group/create/page.tsx, src/features/challenge/components/modal/camera-modal/camera-modal.tsx, src/features/challenge/components/modal/camera-modal/styles.ts, src/features/challenge/components/modal/camera-modal/types.ts, src/features/challenge/components/verification-card/styles.ts, src/features/challenge/components/verification-card/verification-card.tsx, src/features/main/components/introduce/introduce.tsx, src/features/main/components/introduce/styles.ts, src/widgets/challenge/group/[id]/verification/details/challenge-group-verification-details.tsx, src/widgets/challenge/group/[id]/verification/details/styles.ts, src/widgets/challenge/personal/[id]/details/challenge-personal-details.tsx, src/widgets/member/login/styles.ts
> 상호 피드백간 및 QA로 수집한 서비스 개선점들을 반영합니다.
| 이슈 | 내용 |
| --- | --- |
| Closes #419 | 전면 카메라 좌우전환 해제 |
| Closes #396 | 클립보드 복사시 복사되는 경로가 “인증 상세”가 되도록 수정 |
| Closes #418 | Introduce 숫자가 증가함에 따라, 화면이 흔들리는 것을 방지 |
| Closes #420 | 인증 내용 작성 후 렌더링 과정에서 \n 생략 문제 |
| Closes #421 | 개인 챌린지 인증 성공/실패 여부를 버튼에 표시 |
| Closes #422 | 챌린지 시작 날짜가 고정되어 있는 경우 (force-dynamic 설정 필요) |
Relates to #341
=> PR (FE) epic: QA 및 에러 핸들링 

Dockerfile, src/shared/lib/api/utils.ts
> ip 주소와 도커파일 코드 수정
Relates to #429
=> PR:[infra] ip 주소와 도커파일 코드 수정

src/features/challenge/components/modal/camera-modal/camera-modal.tsx, src/shared/components/calender/header/calender-header.tsx
>  달력 현재 월을 바꾸면 폼이 트리거되는 오류
> `type = 'button'` 추가
Relates to #341 
Closes #435
=> fix: 캘린더 월 변경 버튼 클릭 시 폼 트리거 버그

next.config.ts
> next.config S3 이미지 업로드 권한을 허용합니다.
Closes #410
=> FE (PR) feat: S3 이미지 업로드 

src/widgets/member/login/styles.ts
=> PR[style]: 로그인 버튼 스타일 수정

package.json, src/shared/lib/api/utils.ts
=> feat: V3 AWS API 환경 설정 및 도메인 변경
